site_name: CodeNebula
site_url: https://CodeNebula.github.io/


nav:
  - Home: index.md
  - Algorithm: inex.md
  - Paper Interpretion: idex.md
  - Mathematics: 
    - Overview: Mathematics/index.md
    - Game Theory:
      - Overview: Mathematics/Game Theory/index.md
      - Four First Lessons: Mathematics/Game Theory/Four First Lessons.md
      - Iterative Deletion: Mathematics/Game Theory/Iterative Deletion.md
  

theme: 
  name: material
  darkMode: class
  palette:
    
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to the dark mode
      
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
   

  font:
    text: Roboto
    code: Roboto Mono


  features:
    - navigation.instant
    - navigation.instant.prefetch 
    - navigation.instant.progress 
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - navigation.indexes 
    - toc.follow
    - navigation.top 
    - search.suggest 
    - search.highlight
  
extra_css:
  - css/custom.css

# mkdocs.yml
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true  # 使用通用模式，兼容性更好
  - admonition  # 支持 !!!
  - pymdownx.details  # 支持 ???
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
